check_library_exists(ssl SSL_new "" HAVE_SSL_LIB)
if(HAVE_SSL_LIB)
    message(STATUS "Found OpenSSL libraries")
    set(ENABLE_SSL ON)
else()
    message(STATUS "OpenSSL libraries not found")
endif()
